/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DivisionE.java
 *
 * Created on 04 May 2012, 3:30:20 PM
 */

package Grade3;

/**
 *
 * @author ZIPHO LUNIKA
 */
public class DivisionM extends javax.swing.JFrame {

    /** Creates new form DivisionE */
    public DivisionM() {
        initComponents();
    }
 int n1=0;
  int n2=0;
    int score=0;
    int total=0;
    public void generate()
    {
      n1=(int)(Math.random()*100)+2;

       n2=(int)(Math.random()*100)+2;
while(n2%n1!=0)
{
    n1=(int)(Math.random()*100)+1;

       n2=(int)(Math.random()*100)+1;
}
             num1.setText(String.valueOf(n1));
num2.setText(String.valueOf(n2));
    }
    public void mark()
    {
        int ans1=Integer.parseInt(num1.getText());
        int ans2=Integer.parseInt(num2.getText());
        int ans=ans2/ans1;
        int UserAns=Integer.parseInt(Answer.getText());
if(UserAns==ans)
{
    int pic2=(int)(Math.random()*3)+1;

    Pi.setText("√");
               Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grade3/P"+pic2+".gif"))); // NOI18N
    score++;
               total++;
               s.setText(String.valueOf(score));
               t.setText(String.valueOf(total));
               jPanel1.setBackground(new java.awt.Color(102, 255, 0));
                  // jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        }
 else
{
int pic=(int)(Math.random()*4)+1;
            Pi.setText("x");
           Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grade3/N"+pic+".jpg"))); // NOI18N
                  total++;

               t.setText(String.valueOf(total));
//jPanel1.setBackground(new java.awt.Color(102, 255, 0));
                   jPanel1.setBackground(new java.awt.Color(255, 51, 51));
 }
    }
    public void subtract()
    {
        total++;
               t.setText(String.valueOf(total));
        score--;
               s.setText(String.valueOf(score));
    }
public void generateStandard()
    {
      x.setText(String.valueOf(n2));
        y.setText(String.valueOf(n1));
        CAnswer.setText("?");
    }
    public void Correct()
    {
        x.setText(String.valueOf(n2));
        y.setText(String.valueOf(n1));
int ans0=n2/n1;
CAnswer.setText(String.valueOf(ans0));
/*total++;
               t.setText(String.valueOf(total));
score--;
               s.setText(String.valueOf(score));
*/

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        num1 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Answer = new javax.swing.JTextField();
        Picture = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        y = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CAnswer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        Pi = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Division - Medium", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Snap ITC", 1, 36))); // NOI18N
        jPanel1.setLayout(null);

        num1.setFont(new java.awt.Font("La Bamba LET", 1, 36));
        num1.setText("y");
        jPanel1.add(num1);
        num1.setBounds(190, 170, 80, 40);

        num2.setFont(new java.awt.Font("La Bamba LET", 1, 36));
        num2.setText("x");
        jPanel1.add(num2);
        num2.setBounds(250, 170, 190, 40);

        jLabel1.setFont(new java.awt.Font("La Bamba LET", 1, 36));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grade3/devide.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 150, 320, 80);

        Answer.setFont(new java.awt.Font("GulimChe", 1, 36));
        jPanel1.add(Answer);
        Answer.setBounds(220, 110, 220, 40);
        jPanel1.add(Picture);
        Picture.setBounds(570, 50, 330, 300);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 390, 130, 23);

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 420, 110, 23);

        jButton3.setText("Dont Know?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(620, 450, 140, 23);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        x.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        x.setText("x");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        jLabel11.setText("÷");

        y.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        y.setText("y");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        jLabel13.setText("=");

        CAnswer.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        CAnswer.setText("Ans");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(CAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(340, 530, 620, 100);

        jLabel2.setFont(new java.awt.Font("Chiller", 3, 36));
        jLabel2.setText("Score:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 390, 140, 60);

        jLabel3.setFont(new java.awt.Font("Chiller", 3, 36));
        jLabel3.setText("Total:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 510, 110, 50);

        s.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36));
        s.setText("S");
        jPanel1.add(s);
        s.setBounds(200, 394, 90, 50);

        t.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36));
        t.setText("T");
        jPanel1.add(t);
        t.setBounds(210, 504, 90, 48);

        Pi.setFont(new java.awt.Font("Tahoma", 1, 36));
        jPanel1.add(Pi);
        Pi.setBounds(490, 184, 50, 70);

        jMenu1.setText("File");

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Easy");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Hard Mode");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
generate();
generateStandard();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
mark();
Correct();
generate();

//Correct();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Correct();
generate();
subtract();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        new WelcomePage().setVisible(true);

        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        new Division().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
        new DivisionE().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
        new DivisionH().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DivisionM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JLabel CAnswer;
    private javax.swing.JLabel Pi;
    private javax.swing.JLabel Picture;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel s;
    private javax.swing.JLabel t;
    private javax.swing.JLabel x;
    private javax.swing.JLabel y;
    // End of variables declaration//GEN-END:variables

}
