/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EvenOddE.java
 *
 * Created on 06 May 2012, 9:28:46 AM
 */

package Grade3;

/**
 *
 * @author ZIPHO LUNIKA
 */
public class EvenOddE extends javax.swing.JFrame {

    /** Creates new form EvenOddE */
    public EvenOddE() {
        initComponents();
    }
String [] pos={
  "Good Job!"
          ,"Great!"
          ,"Exellent!"
          ,"Wonderful!"
          ,"Brainiac!"
          ,"Genius!"
        };
String [] neg={
  "Not good!"
          ,"No,No,NO"
          ,"Incorrect"
          ,"Practise Some more!"
          ,"!@#$%"
          ,"Concerntrate student!"
};
int score=0;
int total=0;
int num=0;
public void generate()
    {
    num=(int)(Math.random()*50)+1;
   Question.setText(String.valueOf(num));
}
public void mark()
    {
    String ans="";
    String input=Answer.getText();
    if(num%2==0)
    {
        ans="even";
    }
    else
    {
        ans="odd";
    }
    if(ans.equalsIgnoreCase(input))
    {
        TickBox.setText("√");
  int com=(int)(Math.random()*5);
String comm=pos[com];
  comment.setText(comm);
  score++;
  total++;
  s.setText(String.valueOf(score));
  t.setText(String.valueOf(total));
        jPanel1.setBackground(new java.awt.Color(102, 255, 0));

    }
 else
    {
                TickBox.setText("X");
                int com=(int)(Math.random()*5);
String comm=neg[com];
  comment.setText(comm);
  total++;
                   jPanel1.setBackground(new java.awt.Color(255, 51, 51));

    t.setText(String.valueOf(total));

 }
}
public void DontKnow()
     {
     String ans="";
    String input=Answer.getText();
    if(num%2==0)
    {
        ans="even";
    }
    else
    {
        ans="odd";
    }
    jLabel6.setText(String.valueOf(num));
    if(ans.equals("even"))
    {
    jLabel5.setText(",Is an even number");
         }
 else
    {
    jLabel5.setText(",Is a odd number");
   

         }
     score--;
   total++;
    s.setText(String.valueOf(score));

      t.setText(String.valueOf(total));
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Answer = new javax.swing.JTextField();
        TickBox = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Even&Odd Numbers -Easy", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Snap ITC", 1, 24))); // NOI18N
        jPanel1.setLayout(null);

        Question.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jPanel1.add(Question);
        Question.setBounds(49, 107, 458, 55);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 480, 160, 30);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setText("Mark");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 520, 160, 30);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton3.setText("Dont Know?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 560, 160, 30);

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel2.setText("Answer Below Please:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 210, 240, 50);

        Answer.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jPanel1.add(Answer);
        Answer.setBounds(40, 300, 350, 50);

        TickBox.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jPanel1.add(TickBox);
        TickBox.setBounds(324, 204, 80, 80);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 10, 230, 40);

        Number.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jPanel2.add(Number);
        Number.setBounds(0, 10, 0, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 10, 70, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 590, 320, 60);

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel3.setText("Score");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 400, 170, 30);

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel4.setText("Total");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 460, 160, 30);

        s.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        s.setText("S");
        jPanel1.add(s);
        s.setBounds(180, 400, 110, 40);

        t.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        t.setText("T");
        jPanel1.add(t);
        t.setBounds(180, 450, 170, 40);

        comment.setFont(new java.awt.Font("La Bamba LET", 1, 36)); // NOI18N
        jPanel1.add(comment);
        comment.setBounds(420, 200, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grade3/Comment.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 50, 510, 600);

        jMenu1.setText("File");

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Medium Mode");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Hard Mode");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
mark();
  generate();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DontKnow();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
generate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        new WelcomePage().setVisible(true);

        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         this.dispose();
        new EvenOddM().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         this.dispose();
        new EvenOddH().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
this.dispose();
new EvenAndOddMenu().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvenOddE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JLabel Number;
    private javax.swing.JLabel Question;
    private javax.swing.JLabel TickBox;
    private javax.swing.JLabel comment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel s;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables

}
