/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EvenOddE.java
 *
 * Created on 06 May 2012, 9:28:46 AM
 */

package Grade3;

/**
 *
 * @author ZIPHO LUNIKA
 */
public class SequenceM extends javax.swing.JFrame {

    /** Creates new form EvenOddE */
    public SequenceM() {
        initComponents();
    }
String [] pos={
  "Good Job!"
          ,"Great!"
          ,"Excellent!"
          ,"Wonderful!"
          ,"Brainiac!"
          ,"Genius!"
        };
String [] neg={
  "Not good!"
          ,"No,No,NO"
          ,"Incorrect"
          ,"Practise Some more!"
          ,"!@#$%"
          ,"Concerntrate student!"
};
int score=0;
int total=0;
int num=0;
int sq=0;
int dif=0;
public void generate()
    {
    num=(int)(Math.random()*50)+1;
    s1.setText(String.valueOf(num));
      dif=(int)(Math.random()*50)+1;
      sq=num+dif;
          s2.setText(String.valueOf(sq));
sq=sq+dif;
          s3.setText(String.valueOf(sq));
          sq=sq+dif;
          s4.setText(String.valueOf(sq));
          s5.setText("X");
}
public void mark()
    {
 int ans=sq+dif;
int input=Integer.parseInt(s5.getText());
 if(ans==(input))
    {
        TickBox.setText("√");
  int com=(int)(Math.random()*5);
String comm=pos[com];
  comment.setText(comm);
  score++;
  total++;
  s.setText(String.valueOf(score));
  t.setText(String.valueOf(total));
        jPanel1.setBackground(new java.awt.Color(102, 255, 0));

    }
 else
    {
                TickBox.setText("X");
                int com=(int)(Math.random()*5);
String comm=neg[com];
  comment.setText(comm);
  total++;
                   jPanel1.setBackground(new java.awt.Color(255, 51, 51));

    t.setText(String.valueOf(total));

 }
}
public void DontKnow()
     {
         int ans=dif+sq;
   
    jLabel6.setText(String.valueOf(ans));

     score--;
   total++;
    s.setText(String.valueOf(score));

      t.setText(String.valueOf(total));
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        s5 = new javax.swing.JTextField();
        TickBox = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number Patterns-Medium", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Snap ITC", 1, 24))); // NOI18N
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 480, 160, 30);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jButton2.setText("Mark");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 520, 160, 30);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jButton3.setText("Dont Know?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 560, 160, 30);

        s5.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
        jPanel1.add(s5);
        s5.setBounds(300, 230, 70, 50);

        TickBox.setFont(new java.awt.Font("Snap ITC", 0, 36));
        jPanel1.add(TickBox);
        TickBox.setBounds(320, 140, 90, 80);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 10, 230, 40);

        Number.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jPanel2.add(Number);
        Number.setBounds(0, 10, 0, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 10, 70, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 590, 320, 60);

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 36));
        jLabel3.setText("Score");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 400, 170, 30);

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 36));
        jLabel4.setText("Total");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 460, 160, 30);

        s.setFont(new java.awt.Font("Chiller", 1, 36));
        s.setText("S");
        jPanel1.add(s);
        s.setBounds(180, 400, 110, 40);

        t.setFont(new java.awt.Font("Chiller", 1, 36));
        t.setText("T");
        jPanel1.add(t);
        t.setBounds(180, 450, 170, 40);

        comment.setFont(new java.awt.Font("La Bamba LET", 1, 36));
        jPanel1.add(comment);
        comment.setBounds(420, 200, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grade3/Comment.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 50, 510, 600);

        s1.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
        s1.setText(" ");
        jPanel1.add(s1);
        s1.setBounds(10, 220, 70, 70);

        s2.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
        s2.setText(" ");
        jPanel1.add(s2);
        s2.setBounds(70, 230, 40, 50);

        s3.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
        s3.setText(" ");
        jPanel1.add(s3);
        s3.setBounds(130, 230, 40, 50);

        s4.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
        s4.setText(" ");
        jPanel1.add(s4);
        s4.setBounds(200, 230, 80, 50);

        jMenu1.setText("File");

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("Menu");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Easy Mode");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("HardMode");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
mark();
  generate();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DontKnow();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
generate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.hide();
        new WelcomePage().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
        new SequenceMenu().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        new SequenceE().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        new SequenceH().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SequenceM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Number;
    private javax.swing.JLabel TickBox;
    private javax.swing.JLabel comment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel s;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JTextField s5;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables

}
